language: java
jdk: oraclejdk8
sudo: false
install: true
addons:
  sonarcloud:
    organization: "sebez-github"
script:  
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
